name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install workloads
        run: dotnet workload install wasm-tools wasm-experimental

      - name: Build
        run: dotnet build -warnaserror -p:TreatWarningsAsErrors=true

      - name: Test
        run: dotnet test --no-build
